### PR TITLE
Darkmode

### PR DESCRIPTION
**Pull request by chasew2**
### Darkmode
The update adds a dark mode toggle after a user is logged in. 
- Toggle is a slider button in the top right corner that can flip between dark and light mode
- Can move between pages in dark mode without toggling every time
- CSS Style to have dark mode styles
- Header and words have been adjusted

### Minor issues
- Light mode sometimes flashes briefly when moving between pages in dark mode (Likely because html is first rendered in light mode before checking the state of the dark mode toggle

### CODE REVIEW

**Review by EricHarrison72 — CHANGES_REQUESTED** [review]
#### Darkmode ####
The app now has a working darkmode and a light mode, which is unreal. The toggle button is responsive, and it stays in darkmode when switching pages. Everything has been adjusted properly and is still readable in both light and dark modes.

#### The Problems ####
* The new widgets to display weather information don't have a darkmode colour yet, so they stay as the light blue.
* The toggle button defaults to light mode, so if you switch pages while on darkmode you have to press it twice to switch back to light mode.
* The graphs don't have a dark mode (but you knew that already)

**Comment by iansteyn** [comment]
## Some problems I plan to address:
- [ ] Graphs have no darkmode
- [ ] `{% scripts %}` blocks placed in the wrong spot in some templates
- [ ] a few duplicated css classes
- [ ] `select-table` darkmode version has accidental formatting changes

## problems that someone else should address if there's time
- [ ] `darkmode.js` is not tested
- [ ] The toggle buttons sometimes just doesn't work.

**Comment by iansteyn** [comment]
## Ian's last update before he passes away 🪦 
Ok dark mode really is done. Buttons, headers, everything. The user settings page also looks nicer now.

The admin page could use some sprucing up (_why_ is there random bootstrap shit inside it, we don't use bootstrap and therefore it doesn't work) but that will have to wait for another branch if it happens at all. 

### The only problem....
... is the one failing test, which is also a symptom of a bug I have experienced on this branch. There is something wrong with the `try-except` block in `settings()` in `settings.py()`. It doesn't throw the error to the except block. My theory is that it's because the except block's code is itself broken; there is no such template as `error.html`, which it tries to render. But it may be deeper than that. Idk, It's a problem for the morning, and perhaps for Eric or Chase to figure out.

**Review by EricHarrison72 — APPROVED** [review]
Darkmode is finally complete. It works with all aspects of every page, and has been integrated without breaking anything.

**Pull request merged**
