### PR TITLE
Graph Update - class structure, wind & rain graphs, tests

### PR DESCRIPTION
**Pull request by iansteyn**
# Graph Update [edited w/ final commits]
Alright, the (almost) final version of the graphs are here. 

### Class Structure
This branch restructures the prototype code that was in `graphs.py` into an abstract class called `WeatherGraph`. The children of this class provide concrete implementations of its abstract methods, which allows them to re-use similar code while still defining quite different types of graphs.

### New graphs
So this class now has three subclasses, which correspond to the three types of graphs you can view:
- *Temperature graph* - nothing much changed here
- *Wind graph* - polar bar chart, took forever to figure out all the pandas shenanigans, but it looks pretty cool
- *Rain graph* - simple bar chart of rain amount

### Error handling (#170)
If you try to submit a date range that doesn't make sense, an error message will display instead of the site crashing. Try it!

### Tests (#133)
- I wrote hella tests in `test_graphs.py`
- also updated `test_queries.py` and `test_jinja_macros.py`
- STILL REQUIRED: the relevant view function tests. Not doing it here because I think `views.py` as a whole needs an overhaul

### Other
- Cosmetic improvements: the graphs also now use our website fonts (Rubik for titles, Roboto elsewhere), and bar graphs are now more visible for large date ranges.
- Query code, selectors, etc were all updated/tweaked accordingly.
- all graph related stuff had 'past' removed from names, because the 'current' graph features was cut. (#171)

### CODE REVIEW

**Review by chasew2 — COMMENTED** [review]
This review is taking into account the pull request is still unfinished
##Good
Graphs.py 
- Code for basic figures look good (i.e. pastTemp, pastRain, etc)

Queries.py
- Tweaked code for adding spaces implemented correctly
- get_data_in_range correctly queries db for a city's data within range of 2 dates

Graph_past.html.jinja/waether_summary.html.jinja
- So far the htmls look good with frontend changes for readable

##Issues

- Could use a couple notes in code for explaining the figure code process at the top but code is still easy to read
- Tests still required for this draft (Which are currently being written)
- Issues from the dashboard are needed (They will be when the pull request is finalized)

There will be a follow up review after the pull request is complete.

**Comment by iansteyn** [comment]
## Note on merge conflicts
Because of the way I resolved conflicts with main, it days there are still "conflicts"... but  it's really just a problem with Git not recognizing squashed commits that are the same as the commits in main. Whoever merges this should be able to resolve the "conflicts" very easily during the merge itself.

**Review by chasew2 — CHANGES_REQUESTED** [review]
✅ What Works
Able to access wind graph
Able to access rain graph
Able to access temp graph
Multi date section works 
Error handling for invalid dates
### ⚠️ General issues
test_views.py for /graphs

Currently for test_views.py all tests pass but we are missing a test for accessing the graphs page. This could be an error when trying to access the /graphs page due to an issue with the initialization of the TemperatureGraph class. 
-  The error occurs because the TemperatureGraph class is expecting data to be available when it's instantiated, but in the testing environment, the data might not be available.
-  Update the test setup to ensure that the TemperatureGraph class is properly initialized with mock or test data. This can involve either mocking the database queries or providing sample data directly to the TemperatureGraph class during testing.
- You may also need to register and login a user believe accessing the page (see other view tests with login_required)

**Review by chasew2 — APPROVED** [review]
The views test can be updated in another branch so this is good to merge

**Pull request merged**
