### PR TITLE
Admin updates

### PR DESCRIPTION
**Pull request by chasew2**
### All User to City connects
Users can connect their account to a city when registering. 

### Displaying city info on home
After logging in the home city of the user appears on the index page with relevant data being data from June 24, 2017.

### Admin register/login
Admin accounts can be registered through the admin register page which can only be accessed by entering a passcode of 12.

### Admin updating temps 
Admins can update temps on the admin dashboard page, an admin can pick a city and date and then update the max and min temp of that day.

### Settings page 
On the settings page a user can update their email listing status as well as their home city. 

### Testing
Testing done for user to city admin register/login and updating db

### CODE REVIEW

**Review by JoshuaWard9080 — CHANGES_REQUESTED** [review]
There seems to be an error somewhere in the changes, as in this branch it is impossible to register a new user - It crashes the app. The issue appears to be that line 36 of auth.py attempts to grab a String from a form on the page turn into an int that is then placed in city_id, but the field is null.

**Comment by chasew2** [comment]
> There seems to be an error somewhere in the changes, as in this branch it is impossible to register a new user - It crashes the app. The issue appears to be that line 36 of auth.py attempts to grab a String from a form on the page turn into an int that is then placed in city_id, but the field is null.

Register fixed

**Review by JoshuaWard9080 — APPROVED** [review]
Everything is looking great!

I messed around and tested a bunch of uses, such as logging in and out, registering new users, etc... and everything is working very smoothly. Fantastic work!

One thing to note, however, is that the dropdown menus for the cities in the admin dashboard and settings HTML pages implement their own selectpicker menus, but Ian created a macro that we can implement here. A potential change we could make if we have the time for it is for these menus to reference the macro in helpers/selectors.html.jinja so that we aren't re-writing the same code and any future changes to the dropdown design can be made by altering just the one macro.

Fantastic work, and I think it's good to merge!

**Review by EricHarrison72 — CHANGES_REQUESTED** [review]
All the features appear to work as intended. User's accounts now connect with a city, which displays on the home page. Admin's exist and get their dashboard page that's only accessible to them. And the settings page allows user's to change their homecity and email list options after logging in. Well done!

The only issues I see are that the admin's temperature change only accepts integer numbers. But at this point in the project that feature doesn't seem important enough to be worth changing, I think it's good as is.
And the test for admin_dashboard doesn't seem to work properly. The auth.py coverage covers everything nicely except it doesn't hit that function at all. It would be nice to have that covered before we merge.

**Review by EricHarrison72 — APPROVED** [review]
Test coverage is better, everything looks good now

**Pull request merged**
