### PR TITLE
Major Front End Changes: template restructuring, macros, cosmetics

### PR DESCRIPTION
**Pull request by iansteyn**
### [UPDATED after new commits]
Ok so I know I have a million commits but it turns out front end is _finnicky_.

### Feature pages
- The main 4 "feature" pages are now in their own folder. 
- Each feature page has a selection table (custom css class `.select-table`) that contains the dropdown menus it needs. 
- All of these templates extend `base.html.jinja` (before, some of them extended an intermediary `select_date` template)
- `select_location` is removed because its functionality is now built into `weather_summary`

### Selector Macros
- The dropdown selection menus are defined as _**macros**_ in the template `helpers/selectors.hmtl.jinja`
 - Macros are like kind of like functions. They are essentially mini re-usable templates that you can pass parameters to
 - This also means that all our selection is now _**pure HTML**_, the bootstrap component of things has been removed to reduce complexity

### Submit button
- The selection tables also include a "submit" button that reloads the page with the selected city/date etc

### submit.js
- The scripting for the button is contained in three _**reusable**_ functions:
  - `getDateFromSelection( div_id)`
  - `getCityFromSelection( div_id)`
  - `reloadPageWithArgs( url_args)`

## New Cosmetics
- The website isn't weirdly boxed-in anymore
- Custom CSS classes: mentioned above
- new fonts: Rubik Bold for lvl 1 headers, Roboto for everything else

## Testing
- `test_jinja_macros.py` does what it says. This took forever to figure out. 
- `submit.test.js` tests all three functions currently in `submit.js`.

## Graph Functionality
- this branch also happened to end up covering issue #134
- i.e. the past graph page now updates based on selected location and date range. It doesn't work perfectly yet but that is for another branch

### CODE REVIEW

**Review by EricHarrison72 — COMMENTED** [review]
I like the cosmetic changes. Everything looks a lot nicer, and I'm a big fan of moving the city/date selection option into the weather summary page.

The submit button on the map currently does nothing. If you just wanted it to be for submitting specific city filtering then that's fine and it should be working, but if you wanted the submit button to work for the date as well it currently checks with an event listener for each time any date option is changed, meaning the submit button does nothing.  (I can also change this myself while I add the city filtering, just let me know what you think would be better.)

Also, this branch is currently 32 commits behind main so there are likely some merge conflicts waiting for when we try to merge it. We can deal with those during the merging of the pull request. OR you can run `git merge main` from this branch and deal with them locally. I think that would be the better option so that you can test all your changes for this branch with the new features in main before any pull requests, but I'll leave it up to you.

**Comment by iansteyn** [comment]
> The submit button on the map currently does nothing ... (I can also change this myself while I add the city filtering, just let me know what you think would be better.)
- It's not supposed to do anything right now. It's there for the city filtering, but up to you (@EricHarrison72) what you  use it for (or if you use it at all)

> Also, this branch is currently 32 commits behind main so there are likely some merge conflicts waiting for when we try to merge it. ...
- Yup that is true. Resolving conflicts before merge is the right call, I think, since there are son many changes. But we'll get there when we get there.

**Review by EricHarrison72 — APPROVED** [review]
The problems brought up in my previous review were addressed. All tests now pass, everything is good to go.

**Review by JoshuaWard9080 — APPROVED** [review]
The changes look amazing, everything looks much cleaner and the consolidation of pages leads to a much more intuitive user experience. Fantastic work! 

Everything on the app appears to still be working. User logins, login preservation, map functionality, and date and time selection is working just the same as before. I especially like that the user choices for date and location are persistent through the page changes.

Rohit mentioned in the last lab that it might be good to have the selector draw from the database as opposed to manually inputted into the template, but after some looking into it that would require some php, which would add complexity to the app. With the nature of our app and the amount of time left to complete, I'm not sure this would be a worthwhile investment.

Overall, absolutely fantastic work. Looks amazing!

**Pull request merged**
