### PR TITLE
Userid saved now

### PR DESCRIPTION
**Pull request by chasew2**
This branch includes login, login_required, login tracking, and logout functions. All this functions were in the main branch but didn't work because login tracking was bugged. def get_last_user_id(datb) was added to fix this.
This new code checks the table for the previous userId added to the db then adds 1 and saves to new user.
def get_last_user_id() in auth.py.

There is no tests for this code yet, the pull request is for checking if the new login tracking works across our computers first.

### CODE REVIEW

**Review by iansteyn — CHANGES_REQUESTED** [review]
## ✅ What Works 
-  user registration appears to save user info even after closing and re-opening app
- If you try to access a non-authentication URL without logging in, you are forced to go to login page
-  when logged in, only the log-out link now shows

## ⚠️ Problems
#### Flashing on URL change
- weird flashing glitch happens when you try to access another URL and are forced to go to login page
-  also sometimes happens when you go to home page while logged in
- I think this has something to do with a page loading for a split second before you are re-directed

#### User id
- user id currently shows email in browser. 
  - it should show the number for us to be able to debug it, right?
  - Suggestion for later: make it show the name, not the email

#### models.py
- the `flask_login` import in `models.py` doesn't work, but code still does - presumably this is a package that should be in `requirements.txt`
- but `models.py` does not appear to be used anywhere??

## 📝 Other notes
- `.DS_Store` should not be pushed to version control
- default home page when you log in is currently a data-less weather summary page. seems ok, Presumably this will show the user's home city in the future?

**Comment by iansteyn** [comment]
### Update on Page flashing/flickering
Seems like it's a browser problem that is hard to get around. Apparently mostly happens on Chrome (which i use). The code works functionally so I think it's fine to move forward for now. 
- [r/flask - page flickering](https://www.reddit.com/r/flask/comments/x70vzr/page_flickering/)

**Review by iansteyn — APPROVED** [review]
### ✅ Update on user Id
- User id now shows name and number in browser, looks nice
- When I register a new user, they get a new, distinct user id. 
- I can still log in with older users I registered.

**Review by iansteyn — CHANGES_REQUESTED** [review]
## Unit tests required
`auth.py` requires unit tests before merge. I don't think anyone is waiting for this branch, so we might as well.

**Review by chasew2 — COMMENTED** [review]
Tests have been added now

**Review by iansteyn — APPROVED** [review]
Sufficient test coverage has been achieved to warrant merging this to main. There are still some tests that need to be written, but I know Chase is currently working on them.

**Pull request merged**
