### PR TITLE
Summary improvements

### PR DESCRIPTION
**Pull request by EricHarrison72**
## This is a draft, do not merge yet ##
Improved visuals of the weather summary page.
This includes moving the visual improvements from the homepage to the weather summary page. Including a nicer table with ALL the weather information for the city/date, and embedding a graph of the previous week's temperature.

Things I still need to work on before merging:
* Moving the table to the left of the summary/graph, so it fills the page nicer.
* Adjusting size of everything for when page is set to 100% (I was working with my page on 75% and Ian pointed out that it doesn't fit properly at 100)

## Ready for review (April 3rd) ##

* Alignment is now better with the weather details table to the left of the main weather summary & graph
* Selection table for city/date is centered and resized
* Everything is a bit smaller so it fits on 100% (including the header and the home page)
* Fixed bugs involving the rain icon not changing on days where it's raining, and the wind arrows looking squished for some directions

### CODE REVIEW

**Comment by JoshuaWard9080** [comment]
The update looks great! The integration of a graph into the summary page is a great idea. A lot of the info is very well presented and still consistent with the look and feel of the app. 

I do think, however, that the selection bar looks a little strange off onto the left side of the screen, though. With how centered the other elements are, would it look better if the bar was also centered?

**Review by iansteyn — COMMENTED** [review]
# Review _[ of Draft PR ]_
## ✅ Good Stuff
- new table with all the data looks nice, is consistent with our theming
- general new formatting with icons and stuff is nice
- wind direction arrows are a nice touch
- embedded graph spruces the page up too and will help fill space in the final version, nice

## ⚠️ Problems/suggestions
### 🧠 Stuff you already know about because you have a huuuge brain
- table alignment
- zoom level - on that topic, I think we should adjust all pages to display a little more zoomed at at 100% zoom (if that makes sense? - ask me at the meeting)

### 🕺 Style
- button fonts are currently Ariel, we should update the CSS so they are also Roboto - for consistency
- Home page and summary page have large headers that have manually increased font sizes and Roboto font. It would be better practice to makes these `h1` or `h2` headers, and to then edit the CSS for those styles. (This could also increase consistency with other headers that are currently in Rubik)

### 💊 Macro potential!!!
- Since the core parts of the summaries on the home page and the weather summary are very similar... consider putting that code into a jinja macro. It will make it a lot easier to keep changes consistent across pages as you keep tweaking the final visuals.

### 📎Information organization 
#### 🏷️ Labelling
- While the icons look very nice, I think we should also add labels back in (like "low", "wind direction" etc) for the sake of some of our accessibility requirements. It's just good practice to have more than one way of identifying a piece of info; it helps assistive tech like screen readers as well as most humans.
- Could add units to the details table

#### 📋 Ordering
- Low temp should be before high temp, in my opinion

**Comment by EricHarrison72** [comment]
Rain icon doens't work properly on weather summary, arrows are squished

**Review by iansteyn — CHANGES_REQUESTED** [review]
# Review 2
## Good
- labels added to the main weather summary
- things look better on 100% zoom
- table alignment improved

## Code problems in `weather_summary.jinja.html` 
- There is so much logic inside Jinja that...
  1. makes the template hard to read
  1. Should be handled in the Python backend, especially so we can test it properly
  1. Should be moved to macros because it's completely duplicated from the Home page, which means any change in one necessitates a change in the other
- the huge if-else chains for selecting icons seem unnecessary? Again, this should either be handled by the back end or at least made more compact, since (e.g.) you can put the `wind_direction` in the file name
- The information alignment/spacing looks waaaay better but it's still kinda off. I'll try to mess around with it.

## Questions
- There is a ton of Jinja code just for adding spaces back to city names... Why? This used to be handled in `queries.get_weather_data()` with the `add_space()` function.
- What's up with all the date conversion stuff in `views.weather_summary()`?

**Comment by EricHarrison72** [comment]
All Ian's changes for this branch have been merged. This handles the code readability and macro problems that were mentioned earlier.

Note: The views.py file now contains lot of logic that is probably best to be moved into another file, but I think this is a problem we should worry about once everything else we're working on is done since we're running low on time to finish all the refactoring issues and it all still works at the moment.

**Review by iansteyn — APPROVED** [review]
# Review 3 [Post merging #200]
Everything appears to be in good shape, all tests pass. Good catch on the date formatting mismatch.

`views.py` does indeed contain too much logic probably, but like you said - that's not our main concern right now. I already cleaned it up a little from what it was before #200, but it could be cleaner. Definitely an "if we get around to it" type beat.

**Pull request merged**
