### PR TITLE
Registering an account

### PR DESCRIPTION
**Pull request by chasew2**
auth file allows users to register with an email and password

### CODE REVIEW

**Review by EricHarrison72 — COMMENTED** [review]
I ran into 2 small errors with the login() function when testing the webpage.

Line 57: the check_password_hash(...) was giving an 'Invalid hash method' Error. I fixed this by specifying it as bcrypt.check_password_hash(...)

and Line 63: wasn't redirecting to a page as the URL 'index' needed to be specified to 'bp.index'.

After making these 2 changes everything worked for me, so I'll push them into this branch and request someone else to review it as well.

Also, if you haven't already you'll need to download bcrypt into the virtual environment by running 'pip install flask-bcrypt' in the command line before this branch will run.

**Comment by iansteyn** [comment]
> Also, if you haven't already you'll need to download bcrypt into the virtual environment by running 'pip install flask-bcrypt' in the command line before this branch will run.

There's more details in `venv_guide.md`, but reminder: if you are the first to use a new external package, you should add it to the `requirements.txt` file to make it easy for other people to install everything that's needed.

**Review by iansteyn — CHANGES_REQUESTED** [review]
Bugs/Changes required:
- stylesheets not loading
- template inheritance / organization is messy
- consider renaming bp variables for disambiguation

I am currently working on these changes myself; this is just to document the review process.

**Review by iansteyn — APPROVED** [review]

**Review by iansteyn — APPROVED** [review]
OK, so basically I fixed a lot of the problems with template rendering by re-organizing the templates and making them more consistent. I also did some other refactoring: renaming variables, fixing outdated references to old variable/file names,  merging the old and new stylesheets, minor bugfixes.

If Eric approves, we can merge this, but. there are still some...
#### Remaining issues
- We need to be doing way more testing. I didn't add them myself because I don't know how yet either. (see new issues #109 and #110)
- Code exists for the logout feature, but is not yet fully functional. See #111
- Code exists for requiring authentication to use the app, but is not yet fully functional. See #112

Pretty sure these remaining issues were already a work-in-progress and the expectation was not that they work for this branch. Just thought they were worth documenting.

**Pull request merged**
