### PR TITLE
Notification System

### LINKED ISSUE #32: Admin Manual Alert
As an admin, I want to manually send alerts or messages, so that I can inform users of events or issues with the system

### PR DESCRIPTION
**Pull request by JoshuaWard9080**
Notification system is now working. An admin can send emails to users that are signed up for alerts on four different kinds of weather: rainy, windy, and high or low temperatures. The email has unique formatting depending on the weather event and will have all of the correct data points in the email itself. 

There are still some features that are missing and there are a few bugs left to be ironed out. 

- Submitting an alert to be sent out bugs the other form on the admin dashboard. The city list depopulates for the "update weather data" portion.
- As of right now, it is impossible to choose the date for the alert. This will be added in the near future, as the basis for the system is already in the code. It will only require adding in a Selector, adding a form.get(), and passing that variable into the functions. There are already variables that are used throughout the code that will automatically update the required sections and should be relatively trivial.
- It is likely going to bug out if there are null or no data points. If the admin chooses a city in which no people have signed up for, it will probably error out. Same with choosing a weather event to alert where the city has no data points for that event/time. This will also be updated in the near future by implementing some trys and ifs to make sure that it does not error out
- not a bug, but also might include a link in the email to go to the settings page to unsubscribe from the email in the future

Closes #32

### CODE REVIEW

**Review by EricHarrison72 — COMMENTED** [review]
This is a great foundation to finish the email system off of by finishing the things you've listed in the pull request! I've converted this pull request to a draft, so make sure to change that once it's ready to be reviewed again and merged.

I like how everything is formatted and how the system actually works. The tests you wrote are non-trivial and all pass, however there is no test for the admin_alert function yet, so just make sure to write something to test it before finishing up.

Also, the default date for sending alerts is January 1, 2016 (this looks like it's temporary until you code the date selection in). But in case it wasn't temporary the default date should be June 24, 2017 to match the rest of the website.

**Comment by JoshuaWard9080** [comment]
> I like how everything is formatted and how the system actually works. The tests you wrote are non-trivial and all pass, however there is no test for the admin_alert function yet, so just make sure to write something to test it before finishing up.

I'm unsure how to test the admin_alert function since it is essentially just a route to the page. Should I just test to make sure the page is accessible, similarly to how the other route functions are being tested?

**Review by EricHarrison72 — COMMENTED** [review]
The admin alerts look great! All the previously mentioned bugs have been fixed and everything is working as it's supposed to.

As for testing the admin-alert function, it can be done with the new testing that Ian has done in the `fix_view_tests` branch. You can essentially copy and paste his test_admin function then just change the values for a few things so it works on the admin-alert function. 

Once that's done make sure to change this pull request from a draft to open so I can merge it.

**Comment by JoshuaWard9080** [comment]
Added some tests for admin_alert. Fixed a clash in testing from my branch and main branch. I added a few more people into the test db to get better testing for a few functions I wrote, so the default new user id in auth_actions was clashing with a user id that was already in the database. fixed the default user id so that it is actually a unique id that isn't already in the test db

**Pull request merged**
